# Generated by Django 5.0.1 on 2024-03-15 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='appleImages')),
                ('Name', models.CharField(max_length=100)),
                ('Info', models.CharField(max_length=200)),
                ('Cost', models.IntegerField()),
                ('Anchors', models.URLField(default='http://127.0.0.1:8000/APP/')),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Oneplus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='oneplusImages')),
                ('Name', models.CharField(max_length=100)),
                ('Info', models.CharField(max_length=200)),
                ('Cost', models.IntegerField()),
                ('Anchors', models.URLField(default='http://127.0.0.1:8000/APP/')),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Realme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='realmeImages')),
                ('Name', models.CharField(max_length=100)),
                ('Info', models.CharField(max_length=200)),
                ('Cost', models.IntegerField()),
                ('Anchors', models.URLField(default='http://127.0.0.1:8000/APP/')),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Redmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='redmiImages')),
                ('Name', models.CharField(max_length=100)),
                ('Info', models.CharField(max_length=200)),
                ('Cost', models.IntegerField()),
                ('Anchors', models.URLField(default='http://127.0.0.1:8000/APP/')),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Samsung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='samsungImages')),
                ('Name', models.CharField(max_length=100)),
                ('Info', models.CharField(max_length=200)),
                ('Cost', models.IntegerField()),
                ('Anchors', models.URLField(default='http://127.0.0.1:8000/APP/')),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trend1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.apple')),
                ('Trend2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.oneplus')),
                ('Trend3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.redmi')),
                ('Trend4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.samsung')),
            ],
        ),
    ]
