# Generated by Django 5.0.1 on 2024-03-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_paymentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='LastName',
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='FullName',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
