# Generated by Django 5.0.1 on 2024-04-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0011_phonemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='PaymentMode',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
